### ISSUE TITLE
mangle module local function names

### ISSUE THREAD

**Issue by postspectacular** [babel/babili#372] opened 2017-01-13 04:18 UTC
Maybe I'm just a missing a config option, but why doesn't the default behavior mangle non-exported, module internal function names? Do I need to enable a separate plugin? I'm using this invocation:

```
node_modules/.bin/babili --no-comments --compact --minified -o bundle.min.js lib/index.js
```

E.g. This source:

```js
let reallyLongName = (x) => x;

let main = () => reallyLongName(42);
exports.main = main;
```
is turned into:
```js
let reallyLongName=a=>a,main=()=>reallyLongName(42);exports.main=main;
```

However, `reallyLongName` is a non-exported symbol and therefore should/could be mangled...

(My original source is actually in TypeScript)

**Comment by loganfsmyth** [comment] 2017-01-13 05:09
I believe this is covered in https://github.com/babel/babili/pull/210

**Comment by kangax** [comment] 2017-01-17 18:51
Yep, duplicate of #210

**Closed by kangax** 2017-01-17 18:51 UTC
