### ISSUE TITLE
Babili does not seem to understand Octal

### ISSUE THREAD

**Issue by bolinfest** [babel/babili#310] opened 2016-12-01 10:23 UTC
I got the following error:

```
SyntaxError: atom.js: Invalid number (46715:15)
  46713 |     if (typeof mode === 'function' || mode === undefined) {
  46714 |         f = mode;
> 46715 |         mode = 0777 & (~process.umask());
        |                ^
  46716 |     }
  46717 |     if (!made) made = null;
  46718 | 

```

**Comment by bolinfest** [comment] 2016-12-01 10:26
Hmm, this might be a thing where this code is in strict mode (where octals are disallowed). The file I am trying to minify is an 11MB file that I generated via browserify, so I probably ended up with `'use strict'` all over the place and perhaps this is a bad interaction.

Ideally, Babili would just rewrite this for me as the decimal equivalent since it's rewriting a bunch of other stuff, anyway.

**Comment by boopathi** [comment] 2016-12-01 12:00
Yes. Octal literals are not allowed in strict mode.

I don't think browserify adds "use strict" directive to every file unless you explicitly state. 

If the problem is babel parsing in strict mode by default, you can use `sourceType: "script"`

**Comment by boopathi** [comment] 2016-12-01 22:48
Closing this as it's not a bug with babili.

If this is affected by babili then feel free to comment, we can reopen the issue.

**Closed by boopathi** 2016-12-01 22:48 UTC
