### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by damianobarbati** [babel/babili#486] opened 2017-04-02 22:46 UTC
I'm trying to use Babili but nothing happens: I want to run it always, not only with babel_env=production
```
loader: 'babel-loader',
options: {
    cacheDirectory: true,
    babelrc: false,
    compact: true,
    presets: [
        ['env', {
            targets: {
                browsers: 'Chrome >= 56,Safari >= 10.1,iOS >= 10.1'.split(','),
            },
            modules: false,
            useBuiltIns: true,
            debug: true,
        }],
        'stage-0', 'react', 'babili',
    ],
    plugins: [
        'transform-decorators-legacy',
        ['react-css-modules', {
            'generateScopedName': cssScopedName,
            'filetypes': { '.scss': 'postcss-scss' },
        }],
    ],
},
```
What's missing?

**Comment by hzoo** [comment] 2017-04-02 22:46
Hey @damianobarbati! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by boopathi** [comment] 2017-04-02 22:57
Duplicate of #172

There are some issues when used with other presets - especially when with block-scoping. What do you get as the output / What is not working? Can you create a minimal repo which reproduces this issue?

There is also [babili-webpack-plugin](https://github.com/webpack-contrib/babili-webpack-plugin) to use with webpack.

**Comment by damianobarbati** [comment] 2017-04-02 23:03
The plugin version is not working either like being totally ignored.
Here the current repo I'm working on (public) to check it: https://github.com/damianobarbati/mvp
I'll make a minimal version as soon as I can.
@boopathi thanks for taking time to help me :)

**Closed** 2017-04-11 08:55 UTC
Labels: duplicate
